baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'The Artisan Bakery'
theme = 'minimal-bakery'
canonifyURLs = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Menu'
    url = '/menu/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 4
